"""empty message

Revision ID: ac92e3722a56
Revises: d7f881f544ff
Create Date: 2024-01-12 15:00:28.605860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac92e3722a56'
down_revision = 'd7f881f544ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakout',
    sa.Column('break_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('break_title', sa.String(length=200), nullable=False),
    sa.Column('break_image', sa.String(length=120), nullable=True),
    sa.Column('break_status', sa.Enum('1', '0'), nullable=False),
    sa.Column('break_time', sa.DateTime(), nullable=True),
    sa.Column('break_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['break_level'], ['level.level_id'], ),
    sa.PrimaryKeyConstraint('break_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breakout')
    # ### end Alembic commands ###
